-- Drizzle Supabase Migration: 0000_agrilink_initial.sql
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE IF NOT EXISTS "users" (
	"id" serial PRIMARY KEY NOT NULL,
	"uid" text NOT NULL,
	"email" text NOT NULL,
	"full_name" text NOT NULL,
	"phone" text,
	"role" text DEFAULT 'FARMER' NOT NULL,
	"avatar_url" text,
	"organization_name" text,
	"region" text DEFAULT 'Oromia',
	"zone" text,
	"woreda" text,
	"national_id_number" text,
	"tin_number" text,
	"address" text,
	"is_verified" boolean DEFAULT false,
	"status" text DEFAULT 'ACTIVE',
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now(),
	CONSTRAINT "users_uid_unique" UNIQUE("uid"),
	CONSTRAINT "users_email_unique" UNIQUE("email")
);

CREATE TABLE IF NOT EXISTS "products" (
	"id" serial PRIMARY KEY NOT NULL,
	"farmer_id" integer NOT NULL,
	"farm_id" integer,
	"category_id" integer NOT NULL,
	"subcategory_id" integer,
	"name" text NOT NULL,
	"subcategory" text,
	"product_type" text DEFAULT 'FRESH_FOOD' NOT NULL,
	"variety" text,
	"description" text NOT NULL,
	"grade" text DEFAULT 'GRADE_A' NOT NULL,
	"quality_grade" text DEFAULT 'GRADE_A',
	"price_per_unit_etb" double precision NOT NULL,
	"currency" text DEFAULT 'ETB',
	"unit" text DEFAULT 'KG' NOT NULL,
	"available_quantity" double precision DEFAULT 100 NOT NULL,
	"min_order_quantity" double precision DEFAULT 10 NOT NULL,
	"max_order_quantity" double precision,
	"harvest_date" text NOT NULL,
	"production_date" text,
	"expiration_date" text,
	"freshness_status" text DEFAULT 'AVAILABLE_NOW',
	"expected_availability" text DEFAULT 'Immediate',
	"farm_location" text NOT NULL,
	"region" text NOT NULL,
	"zone" text,
	"woreda" text,
	"town_city" text,
	"altitude_meters" integer,
	"origin_details" text,
	"processing_method" text,
	"harvest_year" integer DEFAULT 2026,
	"storage_requirements" text,
	"packaging_type" text,
	"ingredients" text,
	"is_live_animal" boolean DEFAULT false,
	"animal_breed" text,
	"veterinary_certificate" text,
	"images" text[],
	"lot_batch_number" text NOT NULL,
	"quality_score" integer DEFAULT 96,
	"certifications" text[],
	"is_organic" boolean DEFAULT false,
	"is_verified_farmer" boolean DEFAULT true,
	"delivery_availability" text DEFAULT 'ALL_ETHIOPIA',
	"status" text DEFAULT 'ACTIVE' NOT NULL,
	"shelf_life_days" integer DEFAULT 14,
	"attributes" jsonb DEFAULT '{}'::jsonb,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now()
);

CREATE TABLE IF NOT EXISTS "orders" (
	"id" serial PRIMARY KEY NOT NULL,
	"order_number" text NOT NULL,
	"buyer_id" integer NOT NULL,
	"order_type" text DEFAULT 'PRODUCE' NOT NULL,
	"total_amount_etb" double precision NOT NULL,
	"delivery_fee_etb" double precision DEFAULT 0,
	"service_fee_etb" double precision DEFAULT 0,
	"grand_total_etb" double precision NOT NULL,
	"payment_status" text DEFAULT 'PENDING' NOT NULL,
	"order_status" text DEFAULT 'PAID' NOT NULL,
	"delivery_model" text DEFAULT 'DIRECT' NOT NULL,
	"hub_id" integer,
	"delivery_address" text NOT NULL,
	"delivery_region" text NOT NULL,
	"delivery_zone" text,
	"delivery_woreda" text,
	"national_id_number" text,
	"tin_number" text,
	"payer_account_number" text,
	"delivery_contact_name" text NOT NULL,
	"delivery_contact_phone" text NOT NULL,
	"requested_delivery_date" text,
	"actual_delivery_date" text,
	"notes" text,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now(),
	CONSTRAINT "orders_order_number_unique" UNIQUE("order_number")
);

CREATE TABLE IF NOT EXISTS "user_surveys" (
	"id" serial PRIMARY KEY NOT NULL,
	"survey_id" text NOT NULL UNIQUE,
	"user_id" integer,
	"user_email" text,
	"user_role" text DEFAULT 'GENERAL',
	"satisfaction_rating" text NOT NULL,
	"feedback_text" text,
	"created_at" timestamp DEFAULT now()
);
