import { db, initDatabase } from './index.ts';
import {
  users,
  farmerProfiles,
  farms,
  farmFields,
  buyerProfiles,
  productCategories,
  productSubcategories,
  products,
  inputSuppliers,
  inputCategories,
  inputProducts,
  carts,
  cartItems,
  hubs,
  drivers,
  orders,
  orderItems,
  orderStatusHistory,
  payments,
  deliveries,
  hubMovements,
  qualityInspections,
  financeApplications,
  quoteRequests,
  reviews,
  notifications,
  messages,
  auditLogs,
} from './schema.ts';
import { sql } from 'drizzle-orm';

export async function seedDatabase(force = false) {
  try {
    await initDatabase();
    // Check if categories or users already exist
    const existingCats = await db.select().from(productCategories).limit(1);
    if (existingCats.length > 0 && !force) {
      console.log('Database already has seeded data. Skipping initial seeding.');
      return;
    }

    console.log('Seeding AgriLink PostgreSQL database with authentic agricultural marketplace data...');

    // If force re-seeding, clean tables in proper reverse foreign key dependency order
    if (force || existingCats.length > 0) {
      await db.delete(auditLogs);
      await db.delete(messages);
      await db.delete(notifications);
      await db.delete(reviews);
      await db.delete(quoteRequests);
      await db.delete(financeApplications);
      await db.delete(qualityInspections);
      await db.delete(deliveries);
      await db.delete(hubMovements);
      await db.delete(payments);
      await db.delete(orderStatusHistory);
      await db.delete(orderItems);
      await db.delete(orders);
      await db.delete(cartItems);
      await db.delete(carts);
      await db.delete(inputProducts);
      await db.delete(products);
      await db.delete(productSubcategories);
      await db.delete(farmFields);
      await db.delete(farms);
      await db.delete(drivers);
      await db.delete(inputSuppliers);
      await db.delete(buyerProfiles);
      await db.delete(farmerProfiles);
      await db.delete(users);
      await db.delete(hubs);
      await db.delete(inputCategories);
      await db.delete(productCategories);
    }

    // ==========================================
    // 1. SEED 13 PRODUCT CATEGORIES
    // ==========================================
    const categoriesData = await db.insert(productCategories).values([
      {
        name: 'Grains & Cereals',
        slug: 'grains-cereals',
        description: 'Super-white Teff, Sergegna, Red Teff, Durum Milling Wheat, Highland Barley, White & Yellow Maize, Sorghum, Millet, and Highland Oats.',
        icon: 'Wheat',
        imageUrl: 'https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?auto=format&fit=crop&w=800&q=80',
      },
      {
        name: 'Pulses & Legumes',
        slug: 'pulses-legumes',
        description: 'Kabuli Chickpeas, Export Red Lentils, Faba Beans, White Haricot Beans, Red Kidney Beans, Green Split Peas, Grass Peas, and Soybeans.',
        icon: 'Boxes',
        imageUrl: 'https://images.unsplash.com/photo-1515543237350-b3eea1ec8082?auto=format&fit=crop&w=800&q=80',
      },
      {
        name: 'Roots & Tubers',
        slug: 'roots-tubers',
        description: 'Shashemene Highland Potatoes, Chencha Organic White Garlic, Sweet Potatoes, Enset / Kocho, Highland Ginger, Cassava, and Taro (Godere).',
        icon: 'Carrot',
        imageUrl: 'https://images.unsplash.com/photo-1518977676601-b53f82aba655?auto=format&fit=crop&w=800&q=80',
      },
      {
        name: 'Fresh Vegetables',
        slug: 'vegetables',
        description: 'Greenhouse Roma & Slicing Tomatoes, Bombay Red Onions, Mareko Fana Chili, Ethiopian Kale (Gomen), Crisp Cabbage, Carrots, Green Beans, and Peppers.',
        icon: 'Salad',
        imageUrl: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&w=800&q=80',
      },
      {
        name: 'Fresh Fruits',
        slug: 'fruits',
        description: 'Export-grade Hass Avocados, Rift Valley Sweet Papayas, Arba Minch Cavendish Bananas, Guji Mangoes, Highland Strawberries, Citrus, and Pineapples.',
        icon: 'Apple',
        imageUrl: 'https://images.unsplash.com/photo-1523049673857-eb18f1d7b578?auto=format&fit=crop&w=800&q=80',
      },
      {
        name: 'Specialty Coffee',
        slug: 'coffee',
        description: 'Yirgacheffe Washed Grade 1, Sidama Natural Sun-Dried, Guji Specialty Q-Grade, Harar Longberry, Limu, and Roasted Whole Bean & Ground Coffees.',
        icon: 'Coffee',
        imageUrl: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&w=800&q=80',
      },
      {
        name: 'Oilseeds',
        slug: 'oilseeds',
        description: 'Humera White Sesame Seeds, Wollega Sesame, Niger Seed (Noug), Linseed (Flaxseed), Sunflower Seeds, Safflower, and Rapeseed.',
        icon: 'Sun',
        imageUrl: 'https://images.unsplash.com/photo-1508747703725-719777637510?auto=format&fit=crop&w=800&q=80',
      },
      {
        name: 'Spices & Herbs',
        slug: 'spices-herbs',
        description: 'Fresh & Sun-Dried Mareko Berbere Chili, Korarima Cardamom, Ginger Root, Turmeric, Black Cumin (Tikur Azmud), Fenugreek (Abish), and Fresh Rosemary.',
        icon: 'Sparkles',
        imageUrl: 'https://images.unsplash.com/photo-1588879460618-924b172a6b29?auto=format&fit=crop&w=800&q=80',
      },
      {
        name: 'Honey & Bee Products',
        slug: 'honey',
        description: 'Tigray White Honey, Guji Forest Raw Honey, Highland Amber Honey, Natural Honeycomb, Organic Beeswax, Propolis, and Bee Pollen.',
        icon: 'Hexagon',
        imageUrl: 'https://images.unsplash.com/photo-1587049352846-4a222e784d38?auto=format&fit=crop&w=800&q=80',
      },
      {
        name: 'Dairy Products',
        slug: 'dairy',
        description: 'Highland Fresh Raw Milk, Pasteurized Bottled Milk, Ethiopian Spiced Butter (Niter Kibbeh), Traditional Raw Butter, Cottage Cheese (Ayib), and Yogurt.',
        icon: 'Milk',
        imageUrl: 'https://images.unsplash.com/photo-1550583724-b2692b85b150?auto=format&fit=crop&w=800&q=80',
      },
      {
        name: 'Eggs & Poultry',
        slug: 'eggs-poultry',
        description: 'Highland Free-Range Brown Eggs, Commercial Table Eggs, Live Local Sasso Chickens, Broiler Poultry, and Day-old Chicks.',
        icon: 'Egg',
        imageUrl: 'https://images.unsplash.com/photo-1582722872445-44dc5f7e3c8f?auto=format&fit=crop&w=800&q=80',
      },
      {
        name: 'Meat & Livestock',
        slug: 'meat-livestock',
        description: 'Fresh Chilled Highland Beef, Goat Meat, Mutton, Camel Meat, and Live Breeding Livestock (Boran Cattle, Bonga Sheep, Somali Camels).',
        icon: 'Beef',
        imageUrl: 'https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=800&q=80',
      },
      {
        name: 'Farm-Processed Food',
        slug: 'farm-processed',
        description: 'Stone-Milled 100% White Teff Flour, Shiro Milled Legume Blend, Roasted Barley (Kolo), Roasted Flaxseed Snack, Spiced Chili Blends, and Dried Mango.',
        icon: 'Package',
        imageUrl: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=800&q=80',
      },
    ]).returning();

    // Map categories by slug for subcategory creation
    const catMap = new Map(categoriesData.map((c) => [c.slug, c.id]));

    // ==========================================
    // 2. SEED PRODUCT SUBCATEGORIES
    // ==========================================
    await db.insert(productSubcategories).values([
      // Grains
      { categoryId: catMap.get('grains-cereals')!, name: 'White Teff (Magna)', slug: 'white-teff', productType: 'GRAIN' },
      { categoryId: catMap.get('grains-cereals')!, name: 'Red Teff', slug: 'red-teff', productType: 'GRAIN' },
      { categoryId: catMap.get('grains-cereals')!, name: 'Mixed Teff (Sergegna)', slug: 'mixed-teff', productType: 'GRAIN' },
      { categoryId: catMap.get('grains-cereals')!, name: 'Durum Wheat', slug: 'wheat', productType: 'GRAIN' },
      { categoryId: catMap.get('grains-cereals')!, name: 'Barley', slug: 'barley', productType: 'GRAIN' },
      { categoryId: catMap.get('grains-cereals')!, name: 'White Maize / Corn', slug: 'white-maize', productType: 'GRAIN' },
      { categoryId: catMap.get('grains-cereals')!, name: 'Yellow Maize', slug: 'yellow-maize', productType: 'GRAIN' },
      { categoryId: catMap.get('grains-cereals')!, name: 'Sorghum', slug: 'sorghum', productType: 'GRAIN' },
      { categoryId: catMap.get('grains-cereals')!, name: 'Millet', slug: 'millet', productType: 'GRAIN' },
      { categoryId: catMap.get('grains-cereals')!, name: 'Highland Oats', slug: 'oats', productType: 'GRAIN' },

      // Pulses
      { categoryId: catMap.get('pulses-legumes')!, name: 'Chickpeas (Kabuli & Desi)', slug: 'chickpeas', productType: 'PULSE' },
      { categoryId: catMap.get('pulses-legumes')!, name: 'Red Split Lentils', slug: 'lentils', productType: 'PULSE' },
      { categoryId: catMap.get('pulses-legumes')!, name: 'Faba Beans (Horse Beans)', slug: 'faba-beans', productType: 'PULSE' },
      { categoryId: catMap.get('pulses-legumes')!, name: 'White Haricot Beans', slug: 'white-beans', productType: 'PULSE' },
      { categoryId: catMap.get('pulses-legumes')!, name: 'Red Kidney Beans', slug: 'red-kidney-beans', productType: 'PULSE' },
      { categoryId: catMap.get('pulses-legumes')!, name: 'Soybeans', slug: 'soybeans', productType: 'PULSE' },
      { categoryId: catMap.get('pulses-legumes')!, name: 'Green Split Peas', slug: 'field-peas', productType: 'PULSE' },

      // Roots & Tubers
      { categoryId: catMap.get('roots-tubers')!, name: 'Highland Potatoes', slug: 'potatoes', productType: 'ROOT_TUBER' },
      { categoryId: catMap.get('roots-tubers')!, name: 'Sweet Potatoes', slug: 'sweet-potatoes', productType: 'ROOT_TUBER' },
      { categoryId: catMap.get('roots-tubers')!, name: 'Chencha Garlic Bulbs', slug: 'garlic-roots', productType: 'ROOT_TUBER' },
      { categoryId: catMap.get('roots-tubers')!, name: 'Enset / Fermented Kocho', slug: 'enset-kocho', productType: 'ROOT_TUBER' },
      { categoryId: catMap.get('roots-tubers')!, name: 'Fresh Ginger Root', slug: 'ginger-root', productType: 'ROOT_TUBER' },
      { categoryId: catMap.get('roots-tubers')!, name: 'Taro (Godere)', slug: 'taro-godere', productType: 'ROOT_TUBER' },

      // Vegetables
      { categoryId: catMap.get('vegetables')!, name: 'Roma Tomatoes', slug: 'roma-tomatoes', productType: 'VEGETABLE' },
      { categoryId: catMap.get('vegetables')!, name: 'Beefsteak Slicing Tomatoes', slug: 'beefsteak-tomatoes', productType: 'VEGETABLE' },
      { categoryId: catMap.get('vegetables')!, name: 'Red Bombay Onions', slug: 'red-onions', productType: 'VEGETABLE' },
      { categoryId: catMap.get('vegetables')!, name: 'Ethiopian Kale (Gomen)', slug: 'kale-gomen', productType: 'VEGETABLE' },
      { categoryId: catMap.get('vegetables')!, name: 'Head Cabbage', slug: 'cabbage', productType: 'VEGETABLE' },
      { categoryId: catMap.get('vegetables')!, name: 'Crunchy Carrots', slug: 'carrots', productType: 'VEGETABLE' },
      { categoryId: catMap.get('vegetables')!, name: 'Hot Green Chili Pepper', slug: 'green-chili', productType: 'VEGETABLE' },
      { categoryId: catMap.get('vegetables')!, name: 'Ethiopian Berbere Peppers', slug: 'berbere-pepper', productType: 'VEGETABLE' },
      { categoryId: catMap.get('vegetables')!, name: 'Cucumbers', slug: 'cucumbers', productType: 'VEGETABLE' },
      { categoryId: catMap.get('vegetables')!, name: 'Zucchini & Squash', slug: 'zucchini-squash', productType: 'VEGETABLE' },

      // Fruits
      { categoryId: catMap.get('fruits')!, name: 'Hass Export Avocado', slug: 'hass-avocado', productType: 'FRUIT' },
      { categoryId: catMap.get('fruits')!, name: 'Rift Valley Papaya', slug: 'papaya', productType: 'FRUIT' },
      { categoryId: catMap.get('fruits')!, name: 'Arba Minch Cavendish Bananas', slug: 'bananas', productType: 'FRUIT' },
      { categoryId: catMap.get('fruits')!, name: 'Guji Apple Mango', slug: 'mangoes', productType: 'FRUIT' },
      { categoryId: catMap.get('fruits')!, name: 'Highland Fresh Strawberries', slug: 'strawberries', productType: 'FRUIT' },
      { categoryId: catMap.get('fruits')!, name: 'Sweet Oranges & Citrus', slug: 'citrus', productType: 'FRUIT' },
      { categoryId: catMap.get('fruits')!, name: 'Pineapples', slug: 'pineapples', productType: 'FRUIT' },

      // Coffee
      { categoryId: catMap.get('coffee')!, name: 'Yirgacheffe Washed Grade 1', slug: 'yirgacheffe-washed', productType: 'COFFEE' },
      { categoryId: catMap.get('coffee')!, name: 'Sidama Natural Sun-Dried', slug: 'sidama-natural', productType: 'COFFEE' },
      { categoryId: catMap.get('coffee')!, name: 'Guji Specialty Q-Grade', slug: 'guji-specialty', productType: 'COFFEE' },
      { categoryId: catMap.get('coffee')!, name: 'Harar Longberry Arabica', slug: 'harar-arabica', productType: 'COFFEE' },
      { categoryId: catMap.get('coffee')!, name: 'Roasted Coffee Beans', slug: 'roasted-coffee', productType: 'COFFEE' },
      { categoryId: catMap.get('coffee')!, name: 'Artisan Ground Coffee', slug: 'ground-coffee', productType: 'COFFEE' },

      // Oilseeds
      { categoryId: catMap.get('oilseeds')!, name: 'Humera White Sesame', slug: 'humera-sesame', productType: 'OILSEED' },
      { categoryId: catMap.get('oilseeds')!, name: 'Niger Seed (Noug)', slug: 'niger-seed-noug', productType: 'OILSEED' },
      { categoryId: catMap.get('oilseeds')!, name: 'Linseed / Flaxseed', slug: 'linseed-flaxseed', productType: 'OILSEED' },
      { categoryId: catMap.get('oilseeds')!, name: 'Sunflower Seeds', slug: 'sunflower-seeds', productType: 'OILSEED' },

      // Spices & Herbs
      { categoryId: catMap.get('spices-herbs')!, name: 'Sun-Dried Mareko Berbere', slug: 'dried-berbere', productType: 'SPICE' },
      { categoryId: catMap.get('spices-herbs')!, name: 'Korarima Cardamom Pods', slug: 'korarima-cardamom', productType: 'SPICE' },
      { categoryId: catMap.get('spices-herbs')!, name: 'Turmeric Roots', slug: 'turmeric', productType: 'SPICE' },
      { categoryId: catMap.get('spices-herbs')!, name: 'Black Cumin (Tikur Azmud)', slug: 'black-cumin', productType: 'SPICE' },
      { categoryId: catMap.get('spices-herbs')!, name: 'Fresh Farm Rosemary', slug: 'fresh-rosemary', productType: 'HERB' },

      // Honey
      { categoryId: catMap.get('honey')!, name: 'Tigray Highland White Honey', slug: 'tigray-white-honey', productType: 'HONEY' },
      { categoryId: catMap.get('honey')!, name: 'Guji Wild Forest Honey', slug: 'guji-forest-honey', productType: 'HONEY' },
      { categoryId: catMap.get('honey')!, name: 'Raw Highland Honeycomb', slug: 'raw-honeycomb', productType: 'HONEY' },
      { categoryId: catMap.get('honey')!, name: 'Pure Organic Beeswax', slug: 'organic-beeswax', productType: 'HONEY' },

      // Dairy
      { categoryId: catMap.get('dairy')!, name: 'Highland Fresh Raw Milk', slug: 'fresh-milk', productType: 'DAIRY' },
      { categoryId: catMap.get('dairy')!, name: 'Ethiopian Spiced Butter (Niter Kibbeh)', slug: 'niter-kibbeh', productType: 'DAIRY' },
      { categoryId: catMap.get('dairy')!, name: 'Cottage Cheese (Ayib)', slug: 'ayib-cheese', productType: 'DAIRY' },
      { categoryId: catMap.get('dairy')!, name: 'Raw Dairy Butter', slug: 'raw-butter', productType: 'DAIRY' },

      // Eggs & Poultry
      { categoryId: catMap.get('eggs-poultry')!, name: 'Free-Range Highland Brown Eggs', slug: 'free-range-eggs', productType: 'EGG' },
      { categoryId: catMap.get('eggs-poultry')!, name: 'Live Local Sasso Chickens', slug: 'live-chickens', productType: 'POULTRY' },
      { categoryId: catMap.get('eggs-poultry')!, name: 'Chilled Broiler Poultry Meat', slug: 'broiler-meat', productType: 'MEAT' },

      // Meat & Livestock
      { categoryId: catMap.get('meat-livestock')!, name: 'Fresh Prime Beef Cuts', slug: 'prime-beef', productType: 'MEAT' },
      { categoryId: catMap.get('meat-livestock')!, name: 'Highland Goat Meat', slug: 'goat-meat', productType: 'MEAT' },
      { categoryId: catMap.get('meat-livestock')!, name: 'Live Boran Beef Cattle', slug: 'live-cattle', productType: 'LIVESTOCK' },
      { categoryId: catMap.get('meat-livestock')!, name: 'Live Highland Fat-Tail Sheep', slug: 'live-sheep', productType: 'LIVESTOCK' },
      { categoryId: catMap.get('meat-livestock')!, name: 'Live Somali Camel', slug: 'live-camels', productType: 'LIVESTOCK' },

      // Farm Processed
      { categoryId: catMap.get('farm-processed')!, name: '100% Pure White Teff Flour', slug: 'teff-flour', productType: 'PROCESSED_FOOD' },
      { categoryId: catMap.get('farm-processed')!, name: 'Traditional Spiced Shiro Flour', slug: 'shiro-flour', productType: 'PROCESSED_FOOD' },
      { categoryId: catMap.get('farm-processed')!, name: 'Roasted Ethiopian Barley (Kolo)', slug: 'roasted-barley-kolo', productType: 'PROCESSED_FOOD' },
      { categoryId: catMap.get('farm-processed')!, name: 'Dried Organic Mango Slices', slug: 'dried-mango', productType: 'PROCESSED_FOOD' },
    ]);

    // ==========================================
    // 3. SEED LOGISTICS HUBS
    // ==========================================
    await db.insert(hubs).values([
      {
        name: 'Addis Central Cross-Dock Hub',
        code: 'HUB-ADD-01',
        region: 'Addis Ababa',
        city: 'Addis Ababa (Kality Terminal)',
        address: 'Kality Freight Logistics Zone, Ring Road Corridor',
        latitude: 8.9123,
        longitude: 38.7612,
        capacityTons: 600,
        currentStorageTons: 185,
        managerName: 'Tariku Bekele',
        contactPhone: '+251 91 144 8822',
        coldStorageAvailable: true,
      },
      {
        name: 'Adama Fast-Transit Hub',
        code: 'HUB-ADA-02',
        region: 'Oromia',
        city: 'Adama / Nazret',
        address: 'Expressway Gateway, Adama Industrial Zone',
        latitude: 8.5400,
        longitude: 39.2700,
        capacityTons: 450,
        currentStorageTons: 92,
        managerName: 'Kenenisa Gemechu',
        contactPhone: '+251 92 334 1199',
        coldStorageAvailable: true,
      },
      {
        name: 'Hawassa Fresh Produce Hub',
        code: 'HUB-HAW-03',
        region: 'Sidama',
        city: 'Hawassa',
        address: 'Lake Hawassa Agro-Corridor, Plot 44',
        latitude: 7.0504,
        longitude: 38.4955,
        capacityTons: 350,
        currentStorageTons: 74,
        managerName: 'Mulugeta Tadesse',
        contactPhone: '+251 93 555 4321',
        coldStorageAvailable: true,
      },
      {
        name: 'Bahir Dar Tana Hub',
        code: 'HUB-BDR-04',
        region: 'Amhara',
        city: 'Bahir Dar',
        address: 'Tana Logistics Port, Kebele 14',
        latitude: 11.5742,
        longitude: 37.3614,
        capacityTons: 300,
        currentStorageTons: 45,
        managerName: 'Abebech Worku',
        contactPhone: '+251 91 887 6655',
        coldStorageAvailable: true,
      },
      {
        name: 'Dire Dawa Eastern Hub',
        code: 'HUB-DIR-05',
        region: 'Dire Dawa',
        city: 'Dire Dawa',
        address: 'Free Trade Zone Logistics Gate 2',
        latitude: 9.5931,
        longitude: 41.8661,
        capacityTons: 250,
        currentStorageTons: 38,
        managerName: 'Ahmed Hassen',
        contactPhone: '+251 91 556 1234',
        coldStorageAvailable: true,
      },
    ]);

    // ==========================================
    // 4. SEED USERS & VERIFIED FARMERS
    // ==========================================
    const seededUsers = await db.insert(users).values([
      // 0: Farmer 1 (Oromia - Wonji)
      {
        uid: 'user_farmer_bekele',
        email: 'bekele.tadesse@agrilink.et',
        fullName: 'Bekele Tadesse',
        phone: '+251 91 234 5678',
        role: 'FARMER',
        avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=200&q=80',
        organizationName: 'Wonji Horizon Farms & Co-op',
        region: 'Oromia',
        zone: 'East Shewa',
        woreda: 'Adama Woreda',
        address: 'Wonji Gefersa, East Shewa Zone',
        isVerified: true,
      },
      // 1: Farmer 2 (Sidama - Yirgacheffe & Hawassa)
      {
        uid: 'user_farmer_almaz',
        email: 'almaz.desta@agrilink.et',
        fullName: 'Almaz Desta',
        phone: '+251 92 987 6543',
        role: 'FARMER',
        avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=200&q=80',
        organizationName: 'Yirga Micro-Lots & Lakeside Farms',
        region: 'Sidama',
        zone: 'Gedeo Zone / Yirgacheffe',
        woreda: 'Kochere Woreda',
        address: 'Yirgacheffe Highland Highlands, Sidama',
        isVerified: true,
      },
      // 2: Farmer 3 (Amhara - Gojjam & Gondar)
      {
        uid: 'user_farmer_worku',
        email: 'worku.mengistu@agrilink.et',
        fullName: 'Worku Mengistu',
        phone: '+251 91 876 5432',
        role: 'FARMER',
        avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=200&q=80',
        organizationName: 'Gojjam Grain & Honey Cooperative',
        region: 'Amhara',
        zone: 'East Gojjam',
        woreda: 'Dejen Woreda',
        address: 'Dejen Nile Gorge Valley, Amhara',
        isVerified: true,
      },
      // 3: Farmer 4 (Tigray & Somali - Livestock & Honey)
      {
        uid: 'user_farmer_fatima',
        email: 'fatima.abdi@agrilink.et',
        fullName: 'Fatima Abdi & Mohamed',
        phone: '+251 93 456 7890',
        role: 'FARMER',
        avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=200&q=80',
        organizationName: 'Horn Highland Pastoralist Union',
        region: 'Somali',
        zone: 'Fafan Zone',
        woreda: 'Jijiga Woreda',
        address: 'Fafan Plains, Somali Region',
        isVerified: true,
      },
      // 4: Individual Buyer
      {
        uid: 'user_buyer_yonas',
        email: 'yonas.alemu@gmail.com',
        fullName: 'Yonas Alemu',
        phone: '+251 91 445 6677',
        role: 'BUYER',
        avatarUrl: 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?auto=format&fit=crop&w=200&q=80',
        organizationName: 'Bole Fresh Marts',
        region: 'Addis Ababa',
        address: 'Bole Medhanealem, House 842, Addis Ababa',
        isVerified: true,
      },
      // 5: Commercial Buyer
      {
        uid: 'user_business_sara',
        email: 'procurement@skylightaddis.et',
        fullName: 'Sara Kebede',
        phone: '+251 91 556 7788',
        role: 'BUSINESS_BUYER',
        avatarUrl: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=200&q=80',
        organizationName: 'Ethiopian Skylight Hotels & Catering',
        region: 'Addis Ababa',
        address: 'Bole International Airport Corridor, Addis Ababa',
        isVerified: true,
      },
      // 6: Input Supplier
      {
        uid: 'user_supplier_kassahun',
        email: 'kassahun.agro@ethioinputs.et',
        fullName: 'Kassahun Belay',
        phone: '+251 91 667 8899',
        role: 'INPUT_SUPPLIER',
        avatarUrl: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=200&q=80',
        organizationName: 'EthioAgro Certified Seeds & Inputs',
        region: 'Addis Ababa',
        address: 'Gotera Agro Industrial Park, Addis Ababa',
        isVerified: true,
      },
      // 7: Driver
      {
        uid: 'user_driver_dawit',
        email: 'dawit.logistics@agrilink.et',
        fullName: 'Dawit Haile',
        phone: '+251 92 333 4455',
        role: 'DRIVER',
        avatarUrl: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&w=200&q=80',
        organizationName: 'AgriLink Reefer Express Fleet',
        region: 'Oromia',
        address: 'Adama Expressway Depot',
        isVerified: true,
      },
      // 8: Finance Officer
      {
        uid: 'user_finance_helen',
        email: 'helen.girma@cbe.com.et',
        fullName: 'Helen Girma',
        phone: '+251 91 778 9900',
        role: 'FINANCIAL_INSTITUTION',
        avatarUrl: 'https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?auto=format&fit=crop&w=200&q=80',
        organizationName: 'Commercial Bank of Ethiopia (Agri-Credit Division)',
        region: 'Addis Ababa',
        address: 'CBE HQ Tower, Churchill Road, Addis Ababa',
        isVerified: true,
      },
      // 9: Platform Admin
      {
        uid: 'user_admin_haile',
        email: 'admin@agrilink.et',
        fullName: 'Hailemariam Desalegn',
        phone: '+251 91 100 2244',
        role: 'PLATFORM_ADMIN',
        avatarUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=200&q=80',
        organizationName: 'AgriLink National Technology Governance',
        region: 'Addis Ababa',
        address: 'National ICT Park, Bole Kebele 02, Addis Ababa',
        isVerified: true,
      },
    ]).returning();

    // ==========================================
    // 5. SEED FARMER PROFILES & FARMS
    // ==========================================
    const farmer1 = seededUsers[0];
    const farmer2 = seededUsers[1];
    const farmer3 = seededUsers[2];
    const farmer4 = seededUsers[3];

    await db.insert(farmerProfiles).values([
      {
        userId: farmer1.id,
        farmName: 'Wonji Horizon Main Estate',
        region: 'Oromia',
        zone: 'East Shewa',
        woreda: 'Adama',
        totalAreaHectares: 18.5,
        primaryCrops: ['Roma Tomatoes', 'Magna Super-White Teff', 'Hass Avocado', 'Bombay Red Onions'],
        farmingExperienceYears: 14,
        nationalIdNumber: 'ETH-NID-94820194',
        cooperativeMembership: 'Wonji Sugar & Horticulture Union #22',
        bankAccountNumber: '1000293847291',
        bankName: 'Commercial Bank of Ethiopia',
        bio: 'Third-generation commercial horticulture grower specializing in GlobalG.A.P certified greenhouse tomatoes, export-grade Hass avocados, and certified Magna Teff grains.',
        rating: 4.95,
        completedOrdersCount: 248,
        totalProduceSoldTons: 164.5,
        isCertifiedOrganic: true,
      },
      {
        userId: farmer2.id,
        farmName: 'Yirga Highland Micro-Lots & Dairy Farm',
        region: 'Sidama',
        zone: 'Gedeo Zone',
        woreda: 'Kochere',
        totalAreaHectares: 12.0,
        primaryCrops: ['Yirgacheffe Washed Grade 1 Coffee', 'Sidama Natural Coffee', 'Highland Fresh Milk', 'Pure Highland Honey'],
        farmingExperienceYears: 18,
        nationalIdNumber: 'ETH-NID-88492019',
        cooperativeMembership: 'Yirgacheffe Coffee Farmers Cooperative Union (YCFCU)',
        bankAccountNumber: '1000984729103',
        bankName: 'Awash Bank',
        bio: 'Specialty coffee producer at 2,150m altitude with dedicated wet mill processing, certified organic apiary hives, and high-altitude pasture dairy.',
        rating: 4.98,
        completedOrdersCount: 312,
        totalProduceSoldTons: 88.0,
        isCertifiedOrganic: true,
      },
      {
        userId: farmer3.id,
        farmName: 'Gojjam Fertile Highland Collective',
        region: 'Amhara',
        zone: 'East Gojjam',
        woreda: 'Dejen',
        totalAreaHectares: 24.0,
        primaryCrops: ['Durum Wheat', 'Kabuli Chickpeas', 'Red Split Lentils', 'Traditional Spiced Shiro', 'Noug Oilseeds'],
        farmingExperienceYears: 20,
        nationalIdNumber: 'ETH-NID-77291048',
        cooperativeMembership: 'Damot Union Agriculture Cluster',
        bankAccountNumber: '1000384729184',
        bankName: 'Dashen Bank',
        bio: 'Master grain and pulse producer in the deep volcanic soils of Gojjam. Certified outgrower supplier of high-protein durum wheat, export chickpeas, and traditional stone-milled flours.',
        rating: 4.91,
        completedOrdersCount: 184,
        totalProduceSoldTons: 220.0,
        isCertifiedOrganic: true,
      },
      {
        userId: farmer4.id,
        farmName: 'Horn Pastoralist & Livestock Cooperative',
        region: 'Somali',
        zone: 'Fafan Zone',
        woreda: 'Jijiga',
        totalAreaHectares: 50.0,
        primaryCrops: ['Boran Beef Cattle', 'Somali Camels', 'Highland Sheep', 'White Honey', 'Free-Range Eggs'],
        farmingExperienceYears: 25,
        nationalIdNumber: 'ETH-NID-66382019',
        cooperativeMembership: 'Somali Regional Livestock Traders Association',
        bankAccountNumber: '1000492810394',
        bankName: 'Hijra Bank (Sharia Compliant)',
        bio: 'Certified livestock breeder and pastoralist cooperative supplying health-inspected Boran cattle, pure camels, Somali honey, and free-range poultry with official veterinary certificates.',
        rating: 4.94,
        completedOrdersCount: 145,
        totalProduceSoldTons: 95.0,
        isCertifiedOrganic: false,
      },
    ]);

    // Seed Farms
    const farmsData = await db.insert(farms).values([
      {
        farmerId: farmer1.id,
        name: 'Wonji Horizon Main Estate',
        locationName: 'Wonji Gefersa Plot 12B',
        region: 'Oromia',
        latitude: 8.4521,
        longitude: 39.2942,
        sizeHectares: 18.5,
        soilType: 'Volcanic Sandy Loam',
        irrigationType: 'Drip & Awash River Canal',
        certifications: ['GlobalG.A.P', 'Ethiopian Organic Quality Seal', 'Traceable Origin #ET-WNJ-09'],
      },
      {
        farmerId: farmer2.id,
        name: 'Yirga Misty Altitude Estate',
        locationName: 'Kochere Highland Slope, 2150m',
        region: 'Sidama',
        latitude: 6.1622,
        longitude: 38.2054,
        sizeHectares: 12.0,
        soilType: 'Rich Humus Red Clay',
        irrigationType: 'Natural Mountain Spring Mist',
        certifications: ['FairTrade International', 'Rainforest Alliance', 'Q-Grader Certified (Score 89.5)'],
      },
      {
        farmerId: farmer3.id,
        name: 'Gojjam Black Earth Fields',
        locationName: 'Dejen Valley Basin',
        region: 'Amhara',
        latitude: 10.1667,
        longitude: 38.1333,
        sizeHectares: 24.0,
        soilType: 'Heavy Black Vertisol',
        irrigationType: 'Rainfed & Gravity Canal',
        certifications: ['MoA Grain Purity 99.8%', 'Ethiopian Standards Agency Level 1'],
      },
      {
        farmerId: farmer4.id,
        name: 'Fafan Pastoralist Rangeland & Apiary',
        locationName: 'Jijiga Green Belt Pastures',
        region: 'Somali',
        latitude: 9.3500,
        longitude: 42.8000,
        sizeHectares: 50.0,
        soilType: 'Alluvial Loam & Rangeland',
        irrigationType: 'Borehole & Seasonal River Basin',
        certifications: ['National Veterinary Health Approved', 'Halal Export Certified'],
      },
    ]).returning();

    // ==========================================
    // 6. SEED BUYERS, INPUT SUPPLIERS & DRIVERS
    // ==========================================
    const buyer1 = seededUsers[4];
    const buyer2 = seededUsers[5];
    await db.insert(buyerProfiles).values([
      {
        userId: buyer1.id,
        buyerType: 'SUPERMARKET',
        companyName: 'Bole Fresh Marts Ltd',
        tinNumber: '0049281729',
        vatRegistered: true,
        deliveryAddress: 'Bole Medhanealem Commercial District, Addis Ababa',
        preferredPaymentMethod: 'CHAPA',
        creditLimitEtb: 350000,
      },
      {
        userId: buyer2.id,
        buyerType: 'HOTEL',
        companyName: 'Ethiopian Skylight Hotel & Aviation Catering',
        tinNumber: '0098472910',
        vatRegistered: true,
        deliveryAddress: 'Bole International Airport Road, Skylight Culinary Hub, Addis Ababa',
        preferredPaymentMethod: 'CHAPA',
        creditLimitEtb: 1800000,
      },
    ]);

    const supplierUser = seededUsers[6];
    await db.insert(inputSuppliers).values({
      userId: supplierUser.id,
      companyName: 'EthioAgro Certified Seeds & Inputs',
      registrationNumber: 'MOA-INPUT-REG-2024-092',
      contactPhone: '+251 91 667 8899',
      contactEmail: 'orders@ethioinputs.et',
      warehouseLocation: 'Gotera Logistics Park Warehouse 7, Addis Ababa',
      region: 'Addis Ababa',
      isVerified: true,
      rating: 4.95,
      totalProductsCount: 15,
    });

    const driverUser = seededUsers[7];
    await db.insert(drivers).values({
      userId: driverUser.id,
      fullName: 'Dawit Haile',
      phone: '+251 92 333 4455',
      licenseNumber: 'ET-DL-4920194',
      vehicleType: 'ISUZU_NPR_REFRIGERATED_TRUCK',
      vehiclePlateNumber: '3-B49201-AA',
      capacityTons: 5.0,
      hasRefrigeration: true,
      region: 'Addis Ababa & Central Corridor',
      currentStatus: 'AVAILABLE',
      currentLat: 8.9140,
      currentLng: 38.7650,
      rating: 4.97,
      totalDeliveries: 420,
      isVerified: true,
    });

    // ==========================================
    // 7. SEED AUTHENTIC AGRICULTURAL PRODUCTS
    // ==========================================
    const prodGrains = catMap.get('grains-cereals')!;
    const prodPulses = catMap.get('pulses-legumes')!;
    const prodRoots = catMap.get('roots-tubers')!;
    const prodVeg = catMap.get('vegetables')!;
    const prodFruit = catMap.get('fruits')!;
    const prodCoffee = catMap.get('coffee')!;
    const prodOil = catMap.get('oilseeds')!;
    const prodSpices = catMap.get('spices-herbs')!;
    const prodHoney = catMap.get('honey')!;
    const prodDairy = catMap.get('dairy')!;
    const prodEggs = catMap.get('eggs-poultry')!;
    const prodMeat = catMap.get('meat-livestock')!;
    const prodProc = catMap.get('farm-processed')!;

    await db.insert(products).values([
      // 1. GRAIN: Magna Super-White Teff Grain
      {
        farmerId: farmer1.id,
        farmId: farmsData[0].id,
        categoryId: prodGrains,
        name: 'Magna Super-White Teff Grain',
        subcategory: 'White Teff (Magna)',
        productType: 'GRAIN',
        variety: 'Quncho DZ-Cr-387 (Super White)',
        description: 'Pristine, double-cleaned super-white Teff grain harvested from the fertile volcanic black soils of East Shewa. Exceptional purity (99.8%), gluten-free, rich in iron, calcium, and complex carbohydrates.',
        grade: 'PREMIUM',
        qualityGrade: 'PREMIUM',
        pricePerUnitEtb: 11800,
        currency: 'ETB',
        unit: 'QUINTAL',
        availableQuantity: 280,
        minOrderQuantity: 5,
        maxOrderQuantity: 100,
        harvestDate: '2026-08-15',
        freshnessStatus: 'HARVESTED_RECENTLY',
        expectedAvailability: 'Immediate Dispatch',
        farmLocation: 'Wonji & Ada’a Highland Parcel, East Shewa',
        region: 'Oromia',
        zone: 'East Shewa',
        woreda: 'Ada’a / Bishoftu',
        townCity: 'Bishoftu',
        altitudeMeters: 1920,
        harvestYear: 2026,
        storageRequirements: 'Store in cool, dry, pest-free ventilated warehouse (relative humidity < 60%).',
        packagingType: '100kg Triple-Layer PP Woven Bag',
        images: [
          'https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?auto=format&fit=crop&w=800&q=80',
          'https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=800&q=80',
        ],
        lotBatchNumber: 'LOT-WNJ-TEF-2026-08',
        qualityScore: 99,
        certifications: ['Ethiopian Grain Trade Enterprise Seal', 'Purity 99.8% Certified', 'Non-GMO'],
        isOrganic: true,
        isVerifiedFarmer: true,
        status: 'ACTIVE',
        shelfLifeDays: 365,
      },

      // 2. GRAIN: Durum Milling Wheat
      {
        farmerId: farmer3.id,
        farmId: farmsData[2].id,
        categoryId: prodGrains,
        name: 'Highland Durum Milling Wheat',
        subcategory: 'Durum Wheat',
        productType: 'GRAIN',
        variety: 'Utuba / Ude High-Protein Durum',
        description: 'Hard vitreous amber durum grain grown in East Gojjam. Protein content 14.2%, high gluten index, ideal for commercial pasta factories, industrial bakeries, and fine semolina milling.',
        grade: 'GRADE_A',
        qualityGrade: 'GRADE_A',
        pricePerUnitEtb: 7200,
        currency: 'ETB',
        unit: 'QUINTAL',
        availableQuantity: 450,
        minOrderQuantity: 10,
        maxOrderQuantity: 200,
        harvestDate: '2026-08-10',
        freshnessStatus: 'HARVESTED_RECENTLY',
        expectedAvailability: 'Immediate Dispatch',
        farmLocation: 'Dejen Valley Grain Cluster',
        region: 'Amhara',
        zone: 'East Gojjam',
        woreda: 'Dejen',
        townCity: 'Dejen',
        altitudeMeters: 2350,
        harvestYear: 2026,
        storageRequirements: 'Dry grain silo or palleted warehouse.',
        packagingType: '100kg Jute / PP Bag',
        images: [
          'https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?auto=format&fit=crop&w=800&q=80',
        ],
        lotBatchNumber: 'LOT-GJM-WHT-2026-08',
        qualityScore: 96,
        certifications: ['MoA Grain Certification', 'Protein 14.2% Lab Tested'],
        isOrganic: false,
        isVerifiedFarmer: true,
        status: 'ACTIVE',
        shelfLifeDays: 365,
      },

      // 3. PULSES: Kabuli Giant Chickpeas
      {
        farmerId: farmer3.id,
        farmId: farmsData[2].id,
        categoryId: prodPulses,
        name: 'Export-Grade Kabuli Chickpeas',
        subcategory: 'Chickpeas (Kabuli & Desi)',
        productType: 'PULSE',
        variety: 'Arerti Extra-Large Seed',
        description: 'Uniform, cream-colored 8mm-9mm Kabuli chickpeas. Cleaned, sorted, low moisture (<10%), zero foreign matter. Ideal for export, canning, and culinary hummus production.',
        grade: 'PREMIUM',
        qualityGrade: 'PREMIUM',
        pricePerUnitEtb: 145,
        currency: 'ETB',
        unit: 'KG',
        availableQuantity: 12000,
        minOrderQuantity: 50,
        harvestDate: '2026-08-18',
        freshnessStatus: 'HARVESTED_RECENTLY',
        expectedAvailability: 'Immediate Dispatch',
        farmLocation: 'Gondar & Gojjam Outgrower Scheme',
        region: 'Amhara',
        zone: 'East Gojjam',
        woreda: 'Dejen',
        altitudeMeters: 2200,
        harvestYear: 2026,
        storageRequirements: 'Store in dry place on wooden pallets.',
        packagingType: '50kg Double Bag',
        images: [
          'https://images.unsplash.com/photo-1515543237350-b3eea1ec8082?auto=format&fit=crop&w=800&q=80',
        ],
        lotBatchNumber: 'LOT-AMH-CHK-2026-08',
        qualityScore: 98,
        certifications: ['Phytosanitary Export Pass', 'ISO 22000 Ready'],
        isOrganic: true,
        isVerifiedFarmer: true,
        status: 'ACTIVE',
        shelfLifeDays: 365,
      },

      // 4. PULSES: Red Split Lentils
      {
        farmerId: farmer3.id,
        farmId: farmsData[2].id,
        categoryId: prodPulses,
        name: 'Adet High-Altitude Red Lentils',
        subcategory: 'Red Split Lentils',
        productType: 'PULSE',
        variety: 'Derash Highland Crimson',
        description: 'Quick-cooking, deep-orange highland red lentils with delicious earthy aroma. Grown by cooperative outgrowers in crop rotation with teff for natural soil nitrogen fixation.',
        grade: 'GRADE_A',
        qualityGrade: 'GRADE_A',
        pricePerUnitEtb: 125,
        currency: 'ETB',
        unit: 'KG',
        availableQuantity: 8500,
        minOrderQuantity: 25,
        harvestDate: '2026-08-12',
        freshnessStatus: 'HARVESTED_RECENTLY',
        expectedAvailability: 'Immediate Dispatch',
        farmLocation: 'Adet Research Valley, Gojjam',
        region: 'Amhara',
        zone: 'West Gojjam',
        woreda: 'Yilmana Densa',
        altitudeMeters: 2400,
        harvestYear: 2026,
        storageRequirements: 'Dry, insect-free storage.',
        packagingType: '50kg PP Bag',
        images: [
          'https://images.unsplash.com/photo-1515543237350-b3eea1ec8082?auto=format&fit=crop&w=800&q=80',
        ],
        lotBatchNumber: 'LOT-GJM-LNT-2026-08',
        qualityScore: 97,
        certifications: ['Ethiopian Quality Standard'],
        isOrganic: true,
        isVerifiedFarmer: true,
        status: 'ACTIVE',
        shelfLifeDays: 365,
      },

      // 5. ROOTS & TUBERS: Fresh Shashemene Potatoes
      {
        farmerId: farmer1.id,
        farmId: farmsData[0].id,
        categoryId: prodRoots,
        name: 'Fresh Shashemene Highland Potatoes',
        subcategory: 'Highland Potatoes',
        productType: 'ROOT_TUBER',
        variety: 'Jalene & Gudene Red-Skin Elite',
        description: 'High dry-matter (22%) culinary potatoes harvested fresh from volcanic loam soils. Thick skin, minimal skinning, low sugar content, crisp frying and boiling texture.',
        grade: 'GRADE_A',
        qualityGrade: 'GRADE_A',
        pricePerUnitEtb: 48,
        currency: 'ETB',
        unit: 'KG',
        availableQuantity: 15000,
        minOrderQuantity: 100,
        harvestDate: '2026-08-29',
        freshnessStatus: 'HARVESTED_TODAY',
        expectedAvailability: 'Immediate Dispatch',
        farmLocation: 'Shashemene Highland Outgrower Cluster',
        region: 'Oromia',
        zone: 'West Arsi',
        woreda: 'Shashemene Zuria',
        townCity: 'Shashemene',
        altitudeMeters: 2050,
        harvestYear: 2026,
        storageRequirements: 'Keep in ventilated dark wooden crates (10°C - 15°C). Do not expose to direct sunlight.',
        packagingType: '50kg Red Mesh Sacks',
        images: [
          'https://images.unsplash.com/photo-1518977676601-b53f82aba655?auto=format&fit=crop&w=800&q=80',
        ],
        lotBatchNumber: 'LOT-SHS-POT-2026-08',
        qualityScore: 97,
        certifications: ['100% Farm Fresh', 'Pesticide Tested'],
        isOrganic: true,
        isVerifiedFarmer: true,
        status: 'ACTIVE',
        shelfLifeDays: 45,
      },

      // 6. ROOTS & TUBERS: Chencha Organic White Garlic Bulbs
      {
        farmerId: farmer2.id,
        farmId: farmsData[1].id,
        categoryId: prodRoots,
        name: 'Chencha Giant Organic White Garlic',
        subcategory: 'Chencha Garlic Bulbs',
        productType: 'ROOT_TUBER',
        variety: 'Chencha Highland White Pungent',
        description: 'Sun-cured, pungent organic white garlic bulbs with tight protective skins and high allicin content. Grown at 2,700m elevation in the misty Gamo highlands without synthetic chemicals.',
        grade: 'PREMIUM',
        qualityGrade: 'PREMIUM',
        pricePerUnitEtb: 175,
        currency: 'ETB',
        unit: 'KG',
        availableQuantity: 3400,
        minOrderQuantity: 20,
        harvestDate: '2026-08-20',
        freshnessStatus: 'HARVESTED_RECENTLY',
        expectedAvailability: 'Immediate Dispatch',
        farmLocation: 'Chencha Highland Slopes, Gamo',
        region: 'South Ethiopia',
        zone: 'Gamo Zone',
        woreda: 'Chencha',
        townCity: 'Chencha',
        altitudeMeters: 2720,
        harvestYear: 2026,
        storageRequirements: 'Hang in dry breezy shade or breathable netted sacks.',
        packagingType: '25kg Netted Sacks',
        images: [
          'https://images.unsplash.com/photo-1615485290382-441e4d049cb5?auto=format&fit=crop&w=800&q=80',
        ],
        lotBatchNumber: 'LOT-CHN-GAR-2026-08',
        qualityScore: 99,
        certifications: ['Certified Organic', 'Allicin Potency Verified'],
        isOrganic: true,
        isVerifiedFarmer: true,
        status: 'ACTIVE',
        shelfLifeDays: 120,
      },

      // 7. VEGETABLES: Greenhouse Roma Tomatoes
      {
        farmerId: farmer1.id,
        farmId: farmsData[0].id,
        categoryId: prodVeg,
        name: 'Greenhouse Vine-Ripened Roma Tomatoes',
        subcategory: 'Roma Tomatoes',
        productType: 'VEGETABLE',
        variety: 'Ty-Shine Export Hybrid',
        description: 'Firm, uniform deep-red greenhouse Roma tomatoes with thick fleshy walls, low seed count, and superior transport shelf life. Harvested daily with stem-on freshness.',
        grade: 'PREMIUM',
        qualityGrade: 'PREMIUM',
        pricePerUnitEtb: 78,
        currency: 'ETB',
        unit: 'KG',
        availableQuantity: 6500,
        minOrderQuantity: 40,
        harvestDate: '2026-08-30',
        freshnessStatus: 'HARVESTED_TODAY',
        expectedAvailability: 'Immediate Dispatch',
        farmLocation: 'Wonji Greenhouse Sector Alpha',
        region: 'Oromia',
        zone: 'East Shewa',
        woreda: 'Adama',
        townCity: 'Adama',
        altitudeMeters: 1540,
        harvestYear: 2026,
        storageRequirements: 'Store at 12°C - 15°C with stem attached for maximum firmness.',
        packagingType: '20kg Reusable Ventilated Plastic Crates',
        images: [
          'https://images.unsplash.com/photo-1592924357228-91a4daadcfea?auto=format&fit=crop&w=800&q=80',
          'https://images.unsplash.com/photo-1546470427-0d4db154ceb7?auto=format&fit=crop&w=800&q=80',
        ],
        lotBatchNumber: 'LOT-WNJ-TOM-2026-08-30',
        qualityScore: 98,
        certifications: ['GlobalG.A.P', 'Zero Chemical Residue'],
        isOrganic: true,
        isVerifiedFarmer: true,
        status: 'ACTIVE',
        shelfLifeDays: 16,
      },

      // 8. VEGETABLES: Red Bombay Onions
      {
        farmerId: farmer1.id,
        farmId: farmsData[0].id,
        categoryId: prodVeg,
        name: 'Highland Red Bombay Onions',
        subcategory: 'Red Bombay Onions',
        productType: 'VEGETABLE',
        variety: 'Bombay Red Premium Cured',
        description: 'Thoroughly dry cured, deep burgundy color, high pungency red onions with tight skins and low moisture content for extended transit and storage without rotting.',
        grade: 'GRADE_A',
        qualityGrade: 'GRADE_A',
        pricePerUnitEtb: 64,
        currency: 'ETB',
        unit: 'KG',
        availableQuantity: 18000,
        minOrderQuantity: 50,
        harvestDate: '2026-08-25',
        freshnessStatus: 'HARVESTED_RECENTLY',
        expectedAvailability: 'Immediate Dispatch',
        farmLocation: 'Awash Valley Irrigated Fields',
        region: 'Oromia',
        zone: 'East Shewa',
        woreda: 'Wonji',
        altitudeMeters: 1500,
        harvestYear: 2026,
        storageRequirements: 'Dry, well-ventilated storerooms.',
        packagingType: '50kg Red Net Bags',
        images: [
          'https://images.unsplash.com/photo-1508747703725-719777637510?auto=format&fit=crop&w=800&q=80',
        ],
        lotBatchNumber: 'LOT-AWS-ONI-2026-08',
        qualityScore: 96,
        certifications: ['MoA Farm Seal'],
        isOrganic: false,
        isVerifiedFarmer: true,
        status: 'ACTIVE',
        shelfLifeDays: 60,
      },

      // 9. FRUITS: Export Hass Avocados
      {
        farmerId: farmer1.id,
        farmId: farmsData[0].id,
        categoryId: prodFruit,
        name: 'Export-Grade Hass Avocados',
        subcategory: 'Hass Export Avocado',
        productType: 'FRUIT',
        variety: 'Export Hass Grafted',
        description: 'Pebbly-skinned, high dry-matter (24.5% minimum) Hass avocados harvested at peak maturity index. Rich creamy nutty flavor, zero bruising, graded by optical sizing line.',
        grade: 'PREMIUM',
        qualityGrade: 'PREMIUM',
        pricePerUnitEtb: 110,
        currency: 'ETB',
        unit: 'KG',
        availableQuantity: 5500,
        minOrderQuantity: 30,
        harvestDate: '2026-08-28',
        freshnessStatus: 'HARVESTED_RECENTLY',
        expectedAvailability: 'Immediate Dispatch',
        farmLocation: 'Wonji Hass Avocado Orchards',
        region: 'Oromia',
        zone: 'East Shewa',
        woreda: 'Wonji',
        altitudeMeters: 1600,
        harvestYear: 2026,
        storageRequirements: 'Store in pre-cooled cold room (5°C - 7°C) with controlled humidity.',
        packagingType: '4kg / 10kg Export Corrugated Cartons',
        images: [
          'https://images.unsplash.com/photo-1523049673857-eb18f1d7b578?auto=format&fit=crop&w=800&q=80',
        ],
        lotBatchNumber: 'LOT-WNJ-AVO-2026-08',
        qualityScore: 99,
        certifications: ['GlobalG.A.P', 'Fairtrade Certified', 'Phytosanitary Export Pass'],
        isOrganic: true,
        isVerifiedFarmer: true,
        status: 'ACTIVE',
        shelfLifeDays: 21,
      },

      // 10. FRUITS: Rift Valley Sweet Solo Papaya
      {
        farmerId: farmer1.id,
        farmId: farmsData[0].id,
        categoryId: prodFruit,
        name: 'Rift Valley Sweet Solo Papaya',
        subcategory: 'Rift Valley Papaya',
        productType: 'FRUIT',
        variety: 'Solo Sunrise Rift Hybrid',
        description: 'Vibrant salmon-red interior, high brix (13.5°), aromatic sweet flesh with tender texture. Pre-cooled on harvest day to ensure prime retail condition upon arrival.',
        grade: 'GRADE_A',
        qualityGrade: 'GRADE_A',
        pricePerUnitEtb: 45,
        currency: 'ETB',
        unit: 'KG',
        availableQuantity: 4200,
        minOrderQuantity: 20,
        harvestDate: '2026-08-30',
        freshnessStatus: 'HARVESTED_TODAY',
        expectedAvailability: 'Immediate Dispatch',
        farmLocation: 'Lake Ziway North Riparian Fields',
        region: 'Oromia',
        zone: 'East Shewa',
        woreda: 'Batu',
        townCity: 'Batu / Ziway',
        altitudeMeters: 1640,
        harvestYear: 2026,
        storageRequirements: '10°C - 13°C. Do not stack unpadded.',
        packagingType: '15kg Padded Wooden / Cardboard Trays',
        images: [
          'https://images.unsplash.com/photo-1517282009859-f000ec3b26fe?auto=format&fit=crop&w=800&q=80',
        ],
        lotBatchNumber: 'LOT-ZWY-PAP-2026-08',
        qualityScore: 97,
        certifications: ['Ethiopian Quality Standard'],
        isOrganic: true,
        isVerifiedFarmer: true,
        status: 'ACTIVE',
        shelfLifeDays: 10,
      },

      // 11. COFFEE: Yirgacheffe Washed Grade 1
      {
        farmerId: farmer2.id,
        farmId: farmsData[1].id,
        categoryId: prodCoffee,
        name: 'Yirgacheffe Washed Grade 1 Specialty Coffee',
        subcategory: 'Yirgacheffe Washed Grade 1',
        productType: 'COFFEE',
        variety: 'Ethiopian Heirloom / Kurume',
        description: 'Legendary Ethiopian micro-lot specialty coffee. Fully washed, fermented 36 hours in mountain spring water, sun-dried on raised African beds. Bright bergamot citrus, jasmine blossom florals, delicate lemon tea finish. SCA Cup Score: 89.5.',
        grade: 'PREMIUM',
        qualityGrade: 'PREMIUM',
        pricePerUnitEtb: 38000,
        currency: 'ETB',
        unit: 'QUINTAL',
        availableQuantity: 60,
        minOrderQuantity: 1,
        maxOrderQuantity: 20,
        harvestDate: '2026-07-20',
        freshnessStatus: 'AVAILABLE_NOW',
        expectedAvailability: 'Immediate Dispatch',
        farmLocation: 'Kochere Washing Station, Yirgacheffe',
        region: 'Sidama',
        zone: 'Gedeo Zone',
        woreda: 'Kochere',
        townCity: 'Yirgacheffe',
        altitudeMeters: 2150,
        originDetails: 'Micro-lot Farm #08, Gedeo Highland Mist Corridor',
        processingMethod: 'Fully Washed (Spring Fermentation & Sun-Bed Drying)',
        harvestYear: 2026,
        storageRequirements: 'Climate-controlled warehouse, GrainPro hermetic lined sacks, 18°C, 55% RH.',
        packagingType: '60kg GrainPro Hermetic Lined Jute Bag',
        images: [
          'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&w=800&q=80',
          'https://images.unsplash.com/photo-1587734195503-904fca47e0e9?auto=format&fit=crop&w=800&q=80',
        ],
        lotBatchNumber: 'LOT-YRG-COF-2026-Q1',
        qualityScore: 99,
        certifications: ['FairTrade International', 'Rainforest Alliance', 'Organic Ethiopia', 'SCA Q-Grade 89.5'],
        isOrganic: true,
        isVerifiedFarmer: true,
        attributes: {
          cupScore: 89.5,
          flavorNotes: 'Jasmine, Bergamot, Earl Grey, Peach, Cane Sugar',
          moistureContent: '10.8%',
          screenSize: '15/17',
          processingStation: 'Kochere Wet Mill',
        },
        status: 'ACTIVE',
        shelfLifeDays: 540,
      },

      // 12. COFFEE: Sidama Natural Sun-Dried Grade 1
      {
        farmerId: farmer2.id,
        farmId: farmsData[1].id,
        categoryId: prodCoffee,
        name: 'Sidama Natural Sun-Dried Grade 1 Coffee',
        subcategory: 'Sidama Natural Sun-Dried',
        productType: 'COFFEE',
        variety: 'Heirloom 74110 & 74112 Varieties',
        description: 'Full-bodied natural sun-dried specialty coffee dried inside intact ripe coffee cherries on raised beds for 21 days. Heavy blueberry jam sweetness, dark chocolate notes, complex winey finish. SCA Cup Score: 88.75.',
        grade: 'PREMIUM',
        qualityGrade: 'PREMIUM',
        pricePerUnitEtb: 36500,
        currency: 'ETB',
        unit: 'QUINTAL',
        availableQuantity: 75,
        minOrderQuantity: 1,
        maxOrderQuantity: 25,
        harvestDate: '2026-07-28',
        freshnessStatus: 'AVAILABLE_NOW',
        expectedAvailability: 'Immediate Dispatch',
        farmLocation: 'Bensa Highland Parcel, Sidama',
        region: 'Sidama',
        zone: 'Bensa Zone',
        woreda: 'Bensa',
        altitudeMeters: 2280,
        originDetails: 'Bensa High-Altitude Forest Fringe',
        processingMethod: 'Natural / Sun-Dried on Raised African Beds (21 Days)',
        harvestYear: 2026,
        storageRequirements: 'GrainPro lined jute sacks in humidity-controlled dry depot.',
        packagingType: '60kg GrainPro Jute Sacks',
        images: [
          'https://images.unsplash.com/photo-1587734195503-904fca47e0e9?auto=format&fit=crop&w=800&q=80',
          'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&w=800&q=80',
        ],
        lotBatchNumber: 'LOT-SDM-COF-2026-N1',
        qualityScore: 98,
        certifications: ['Rainforest Alliance', 'Single Origin Verified', 'SCA Q-Grade 88.75'],
        isOrganic: true,
        isVerifiedFarmer: true,
        attributes: {
          cupScore: 88.75,
          flavorNotes: 'Blueberry, Dried Strawberry, Dark Cocoa, Honeycomb',
          moistureContent: '11.2%',
        },
        status: 'ACTIVE',
        shelfLifeDays: 540,
      },

      // 13. OILSEEDS: Humera Whitish Sesame Seeds
      {
        farmerId: farmer3.id,
        farmId: farmsData[2].id,
        categoryId: prodOil,
        name: 'Humera Pure Whitish Sesame Seeds',
        subcategory: 'Humera White Sesame',
        productType: 'OILSEED',
        variety: 'Humera Grade A Whitish',
        description: 'World-renowned Ethiopian Humera white sesame seeds famous for sweet nutty aroma and high oil content (>52%). Machine cleaned, 99.5% purity, zero GMOs, export ready.',
        grade: 'PREMIUM',
        qualityGrade: 'PREMIUM',
        pricePerUnitEtb: 195,
        currency: 'ETB',
        unit: 'KG',
        availableQuantity: 25000,
        minOrderQuantity: 100,
        harvestDate: '2026-08-05',
        freshnessStatus: 'HARVESTED_RECENTLY',
        expectedAvailability: 'Immediate Dispatch',
        farmLocation: 'Humera Agro-Export Corridor',
        region: 'Tigray',
        zone: 'Western Tigray',
        woreda: 'Setit Humera',
        townCity: 'Humera',
        altitudeMeters: 620,
        harvestYear: 2026,
        storageRequirements: 'Store in cool dry warehouse (RH < 50%).',
        packagingType: '50kg PP Woven Bags with PE liner',
        images: [
          'https://images.unsplash.com/photo-1508747703725-719777637510?auto=format&fit=crop&w=800&q=80',
        ],
        lotBatchNumber: 'LOT-HMR-SES-2026-08',
        qualityScore: 99,
        certifications: ['Export Quality Seal', 'Oil Content 52.8% Verified'],
        isOrganic: true,
        isVerifiedFarmer: true,
        status: 'ACTIVE',
        shelfLifeDays: 365,
      },

      // 14. SPICES & HERBS: Sun-Dried Mareko Berbere Chili
      {
        farmerId: farmer1.id,
        farmId: farmsData[0].id,
        categoryId: prodSpices,
        name: 'Sun-Dried Mareko Fana Berbere Chili Pods',
        subcategory: 'Sun-Dried Mareko Berbere',
        productType: 'SPICE',
        variety: 'Mareko Fana Traditional Red',
        description: 'Whole stemless, naturally sun-cured crimson berbere chili peppers. Intense fragrant aroma, deep natural red color value (ASTA 140+), medium-high pungency.',
        grade: 'GRADE_A',
        qualityGrade: 'GRADE_A',
        pricePerUnitEtb: 220,
        currency: 'ETB',
        unit: 'KG',
        availableQuantity: 4200,
        minOrderQuantity: 10,
        harvestDate: '2026-08-22',
        freshnessStatus: 'HARVESTED_RECENTLY',
        expectedAvailability: 'Immediate Dispatch',
        farmLocation: 'Mareko Valley Spices, Gurage',
        region: 'Central Ethiopia',
        zone: 'Gurage Zone',
        woreda: 'Mareko',
        altitudeMeters: 1780,
        harvestYear: 2026,
        storageRequirements: 'Airtight packaging in dark dry pantry.',
        packagingType: '25kg Polyethylene Lined Sacks',
        images: [
          'https://images.unsplash.com/photo-1588879460618-924b172a6b29?auto=format&fit=crop&w=800&q=80',
        ],
        lotBatchNumber: 'LOT-MRK-BER-2026-08',
        qualityScore: 98,
        certifications: ['ASTA Color Certified', 'Aflatoxin Tested Clean'],
        isOrganic: true,
        isVerifiedFarmer: true,
        status: 'ACTIVE',
        shelfLifeDays: 365,
      },

      // 15. SPICES & HERBS: Whole Korarima Cardamom Pods
      {
        farmerId: farmer2.id,
        farmId: farmsData[1].id,
        categoryId: prodSpices,
        name: 'Wild Highland Korarima (Ethiopian Black Cardamom)',
        subcategory: 'Korarima Cardamom Pods',
        productType: 'SPICE',
        variety: 'Wild Forest Large Pod (Aframomum corrorima)',
        description: 'Sun-dried wild highland korarima pods harvested from the misty southwestern rainforests. Pungent eucalyptus, mint, and warm citrus notes. Indispensable for authentic Ethiopian stews, kibbeh, and specialty coffees.',
        grade: 'PREMIUM',
        qualityGrade: 'PREMIUM',
        pricePerUnitEtb: 480,
        currency: 'ETB',
        unit: 'KG',
        availableQuantity: 1500,
        minOrderQuantity: 5,
        harvestDate: '2026-08-15',
        freshnessStatus: 'HARVESTED_RECENTLY',
        expectedAvailability: 'Immediate Dispatch',
        farmLocation: 'Kaffa Ancient Rainforest Canopy',
        region: 'Southwest Ethiopia',
        zone: 'Kaffa Zone',
        woreda: 'Bonga',
        altitudeMeters: 1950,
        harvestYear: 2026,
        storageRequirements: 'Store sealed in moisture-proof packaging.',
        packagingType: '10kg Sealed Kraft Bags',
        images: [
          'https://images.unsplash.com/photo-1588879460618-924b172a6b29?auto=format&fit=crop&w=800&q=80',
        ],
        lotBatchNumber: 'LOT-KFA-KOR-2026-08',
        qualityScore: 99,
        certifications: ['Wild Harvest Certified', 'Organic Rainforest Protected'],
        isOrganic: true,
        isVerifiedFarmer: true,
        status: 'ACTIVE',
        shelfLifeDays: 730,
      },

      // 16. HONEY: Tigray Highland White Honey
      {
        farmerId: farmer4.id,
        farmId: farmsData[3].id,
        categoryId: prodHoney,
        name: 'Tigray Organic Highland Pure White Honey',
        subcategory: 'Tigray Highland White Honey',
        productType: 'HONEY',
        variety: 'Highland Becium Grandiflorum Blossom',
        description: 'Exquisite creamy white honey harvested from the arid highland blossom flowers of northern Tigray. Naturally crystallized, smooth velvety spread texture, floral delicate aroma with zero sugar additives.',
        grade: 'PREMIUM',
        qualityGrade: 'PREMIUM',
        pricePerUnitEtb: 650,
        currency: 'ETB',
        unit: 'KG',
        availableQuantity: 2800,
        minOrderQuantity: 5,
        harvestDate: '2026-08-10',
        freshnessStatus: 'HARVESTED_RECENTLY',
        expectedAvailability: 'Immediate Dispatch',
        farmLocation: 'Agame Highlands Apiary Network',
        region: 'Tigray',
        zone: 'Eastern Tigray',
        woreda: 'Ganta Afeshum',
        townCity: 'Adigrat',
        altitudeMeters: 2450,
        originDetails: 'Pristine mountain floral pastures (Becium Grandiflorum / Tebeb)',
        harvestYear: 2026,
        storageRequirements: 'Store in airtight jars at ambient room temperature. Do not refrigerate.',
        packagingType: '1kg / 5kg Food-Grade Airtight Glass Jars & Pails',
        images: [
          'https://images.unsplash.com/photo-1587049352846-4a222e784d38?auto=format&fit=crop&w=800&q=80',
        ],
        lotBatchNumber: 'LOT-TGY-HON-2026-W1',
        qualityScore: 99,
        certifications: ['100% Raw Unpasteurized', 'Purity Lab Verified (Moisture 16.4%)', 'Organic Apiculture Seal'],
        isOrganic: true,
        isVerifiedFarmer: true,
        attributes: {
          pollenSource: 'Becium Grandiflorum (Tebeb)',
          moistureContent: '16.4%',
          color: 'Extra White Creamy',
          processing: 'Cold Extracted & Unheated',
        },
        status: 'ACTIVE',
        shelfLifeDays: 730,
      },

      // 17. HONEY: Guji Wild Forest Raw Amber Honey
      {
        farmerId: farmer2.id,
        farmId: farmsData[1].id,
        categoryId: prodHoney,
        name: 'Guji Wild Mountain Forest Raw Honey',
        subcategory: 'Guji Wild Forest Honey',
        productType: 'HONEY',
        variety: 'Wild Forest Canopy Multi-Floral',
        description: 'Deep amber raw honey sourced from traditional hanging log hives in the ancient Guji cloud forests. Rich smoky malt undertones, high enzyme activity, 100% unpasteurized.',
        grade: 'PREMIUM',
        qualityGrade: 'PREMIUM',
        pricePerUnitEtb: 520,
        currency: 'ETB',
        unit: 'KG',
        availableQuantity: 3600,
        minOrderQuantity: 5,
        harvestDate: '2026-08-14',
        freshnessStatus: 'HARVESTED_RECENTLY',
        expectedAvailability: 'Immediate Dispatch',
        farmLocation: 'Guji Cloud Forest Apiary Reserve',
        region: 'Oromia',
        zone: 'Guji Zone',
        woreda: 'Shakisso',
        altitudeMeters: 2200,
        harvestYear: 2026,
        storageRequirements: 'Ambient dry pantry storage.',
        packagingType: '5kg Sealed Buckets & 1kg Jars',
        images: [
          'https://images.unsplash.com/photo-1587049352846-4a222e784d38?auto=format&fit=crop&w=800&q=80',
        ],
        lotBatchNumber: 'LOT-GUJ-HON-2026-08',
        qualityScore: 98,
        certifications: ['Wild Forest Certified', 'MoA Apiculture Standard'],
        isOrganic: true,
        isVerifiedFarmer: true,
        status: 'ACTIVE',
        shelfLifeDays: 730,
      },

      // 18. DAIRY: Ethiopian Clarified Spiced Butter (Niter Kibbeh)
      {
        farmerId: farmer2.id,
        farmId: farmsData[1].id,
        categoryId: prodDairy,
        name: 'Traditional Ethiopian Spiced Butter (Niter Kibbeh)',
        subcategory: 'Ethiopian Spiced Butter (Niter Kibbeh)',
        productType: 'DAIRY',
        variety: 'Highland Clarified Butter with Kosseret & Spices',
        description: 'Artisanal clarified butter slowly simmered with highland herbs (kosseret, korarima, turmeric, garlic, ginger, and fenugreek). Golden color, mouthwatering traditional aroma, shelf-stable.',
        grade: 'PREMIUM',
        qualityGrade: 'PREMIUM',
        pricePerUnitEtb: 780,
        currency: 'ETB',
        unit: 'KG',
        availableQuantity: 1200,
        minOrderQuantity: 2,
        harvestDate: '2026-08-25',
        productionDate: '2026-08-25',
        expirationDate: '2027-02-25',
        freshnessStatus: 'HARVESTED_RECENTLY',
        expectedAvailability: 'Immediate Dispatch',
        farmLocation: 'Hawassa Dairy Co-op Creamery',
        region: 'Sidama',
        zone: 'Sidama Zone',
        woreda: 'Hawassa Zuria',
        townCity: 'Hawassa',
        altitudeMeters: 1700,
        ingredients: 'Pure grass-fed cow butter, kosseret, korarima, turmeric, ginger, garlic, fenugreek, sacred basil.',
        storageRequirements: 'Store in cool dry place or refrigerate after opening.',
        packagingType: '1kg / 2.5kg Airtight Food-Grade Tins & Jars',
        images: [
          'https://images.unsplash.com/photo-1550583724-b2692b85b150?auto=format&fit=crop&w=800&q=80',
        ],
        lotBatchNumber: 'LOT-SID-KIB-2026-08',
        qualityScore: 99,
        certifications: ['MoA Food Safety Approved', '100% Grass-Fed Dairy'],
        isOrganic: true,
        isVerifiedFarmer: true,
        status: 'ACTIVE',
        shelfLifeDays: 180,
      },

      // 19. DAIRY: Fresh Highland Raw Pasteurized Milk
      {
        farmerId: farmer2.id,
        farmId: farmsData[1].id,
        categoryId: prodDairy,
        name: 'Highland Fresh Whole Milk (Chilled Cold-Chain)',
        subcategory: 'Highland Fresh Raw Milk',
        productType: 'DAIRY',
        variety: 'Pure Grass-Fed Whole Cow Milk (3.8% Butterfat)',
        description: 'Fresh, rich, unadulterated whole milk from grass-grazed highland dairy herds. Rapidly chilled to 4°C directly at the milking parlour. Transported via AgriLink refrigerated cold-chain vans.',
        grade: 'GRADE_A',
        qualityGrade: 'GRADE_A',
        pricePerUnitEtb: 65,
        currency: 'ETB',
        unit: 'LITER',
        availableQuantity: 2500,
        minOrderQuantity: 10,
        harvestDate: '2026-08-30',
        productionDate: '2026-08-30',
        expirationDate: '2026-09-04',
        freshnessStatus: 'HARVESTED_TODAY',
        expectedAvailability: 'Immediate Dispatch (Cold Chain)',
        farmLocation: 'Hawassa Lakeside Pasture Creamery',
        region: 'Sidama',
        zone: 'Sidama Zone',
        woreda: 'Hawassa Zuria',
        altitudeMeters: 1750,
        storageRequirements: 'REFRIGERATION MANDATORY: Keep strictly between 2°C and 4°C.',
        packagingType: '5-Liter & 10-Liter Food-Grade Sanitized Cold Jugs',
        images: [
          'https://images.unsplash.com/photo-1550583724-b2692b85b150?auto=format&fit=crop&w=800&q=80',
        ],
        lotBatchNumber: 'LOT-DAI-MLK-2026-08-30',
        qualityScore: 98,
        certifications: ['Veterinary Somatic Cell Tested', 'Cold-Chain Telemetry Verified'],
        isOrganic: true,
        isVerifiedFarmer: true,
        status: 'ACTIVE',
        shelfLifeDays: 5,
      },

      // 20. EGGS & POULTRY: Highland Free-Range Brown Eggs
      {
        farmerId: farmer4.id,
        farmId: farmsData[3].id,
        categoryId: prodEggs,
        name: 'Highland Free-Range Farm Brown Eggs',
        subcategory: 'Free-Range Highland Brown Eggs',
        productType: 'EGG',
        variety: 'Pastured Dual-Purpose Local Hens',
        description: 'Nutrient-rich golden-yolk brown eggs from hens free to forage on organic pastures, grains, and green forage. Collected daily, candled, graded for size, and packed in reinforced pulp trays.',
        grade: 'PREMIUM',
        qualityGrade: 'PREMIUM',
        pricePerUnitEtb: 18,
        currency: 'ETB',
        unit: 'PIECE',
        availableQuantity: 18000,
        minOrderQuantity: 60,
        harvestDate: '2026-08-30',
        freshnessStatus: 'HARVESTED_TODAY',
        expectedAvailability: 'Immediate Dispatch',
        farmLocation: 'Jijiga Green Belt Poultry Pastures',
        region: 'Somali',
        zone: 'Fafan Zone',
        woreda: 'Jijiga',
        altitudeMeters: 1650,
        harvestYear: 2026,
        storageRequirements: 'Cool ventilated egg storage (12°C - 16°C).',
        packagingType: '30-Egg Molded Pulp Cartons / 360-Egg Master Box',
        images: [
          'https://images.unsplash.com/photo-1582722872445-44dc5f7e3c8f?auto=format&fit=crop&w=800&q=80',
        ],
        lotBatchNumber: 'LOT-PLT-EGG-2026-08-30',
        qualityScore: 99,
        certifications: ['Free-Range Humane Certified', 'Candled Grade AA'],
        isOrganic: true,
        isVerifiedFarmer: true,
        status: 'ACTIVE',
        shelfLifeDays: 30,
      },

      // 21. LIVESTOCK: Live Boran Breeding Beef Cattle
      {
        farmerId: farmer4.id,
        farmId: farmsData[3].id,
        categoryId: prodMeat,
        name: 'Purebred Boran Breeding Bull / Steer (Live)',
        subcategory: 'Live Boran Beef Cattle',
        productType: 'LIVESTOCK',
        variety: 'Ethiopian Pure Boran Zebu',
        description: 'Hardy, tick-resistant purebred Boran cattle raised on natural open rangelands. Average live weight 380kg - 450kg. Inspected by Ministry of Agriculture veterinary officers, ear-tagged, vaccinated against FMD and CBPP.',
        grade: 'PREMIUM',
        qualityGrade: 'PREMIUM',
        pricePerUnitEtb: 75000,
        currency: 'ETB',
        unit: 'ANIMAL',
        availableQuantity: 45,
        minOrderQuantity: 1,
        maxOrderQuantity: 10,
        harvestDate: '2026-08-20',
        freshnessStatus: 'AVAILABLE_NOW',
        expectedAvailability: 'Immediate Livestock Transport Trucking',
        farmLocation: 'Fafan Plains Rangeland',
        region: 'Somali',
        zone: 'Fafan Zone',
        woreda: 'Jijiga',
        altitudeMeters: 1600,
        isLiveAnimal: true,
        animalBreed: 'Purebred Boran Zebu',
        veterinaryCertificate: 'ETH-VET-QUARANTINE-2026-9482',
        storageRequirements: 'Ventilated live animal transport with fresh water and forage stops.',
        packagingType: 'Live Cattle Flatbed Transport with Side Railings',
        images: [
          'https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=800&q=80',
        ],
        lotBatchNumber: 'LOT-LIV-BOR-2026-08',
        qualityScore: 98,
        certifications: ['National Vet Health Certificate', 'Ear-Tag Traceability #ET-SOM-4482'],
        isOrganic: true,
        isVerifiedFarmer: true,
        attributes: {
          averageWeightKg: 420,
          ageMonths: 28,
          healthStatus: 'Vaccinated & De-wormed',
          earTagPrefix: 'ET-BOR-',
        },
        status: 'ACTIVE',
        shelfLifeDays: 90,
      },

      // 22. MEAT: Prime Fresh Chilled Highland Beef Cut
      {
        farmerId: farmer4.id,
        farmId: farmsData[3].id,
        categoryId: prodMeat,
        name: 'Prime Grass-Fed Highland Beef Carcass / Cuts',
        subcategory: 'Fresh Prime Beef Cuts',
        productType: 'MEAT',
        variety: 'Pastured Steer Prime Cuts',
        description: 'Freshly dressed, chilled prime beef from pasture-raised cattle slaughtered at export-licensed municipal abattoirs. Inspected, stamped Halal, transported at 1°C in refrigerated vans.',
        grade: 'GRADE_A',
        qualityGrade: 'GRADE_A',
        pricePerUnitEtb: 480,
        currency: 'ETB',
        unit: 'KG',
        availableQuantity: 3500,
        minOrderQuantity: 20,
        harvestDate: '2026-08-30',
        productionDate: '2026-08-30',
        expirationDate: '2026-09-06',
        freshnessStatus: 'HARVESTED_TODAY',
        expectedAvailability: 'Immediate Cold-Chain Dispatch',
        farmLocation: 'Adama Meat Inspection & Abattoir Facility',
        region: 'Oromia',
        zone: 'East Shewa',
        woreda: 'Adama',
        altitudeMeters: 1540,
        storageRequirements: 'Strict Cold-Chain (0°C to 2°C).',
        packagingType: 'Vacuum-Sealed Food Grade Meat Packs',
        images: [
          'https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=800&q=80',
        ],
        lotBatchNumber: 'LOT-MEA-BEF-2026-08-30',
        qualityScore: 98,
        certifications: ['Halal Slaughter Certified', 'MoA Meat Inspection Stamp'],
        isOrganic: true,
        isVerifiedFarmer: true,
        status: 'ACTIVE',
        shelfLifeDays: 7,
      },

      // 23. PROCESSED FOOD: 100% Pure Ada'a White Teff Flour
      {
        farmerId: farmer1.id,
        farmId: farmsData[0].id,
        categoryId: prodProc,
        name: 'Stone-Milled 100% Magna White Teff Flour',
        subcategory: '100% Pure White Teff Flour',
        productType: 'PROCESSED_FOOD',
        variety: 'Ada’a Magna Super-White Pure Flour',
        description: 'Authentic stone-milled Teff flour ground from double-cleaned Quncho grain. 100% pure with zero fillers or wheat blending. High fermentation yield, makes fluffy, light, eye-patterned (Ayn-rich) Injera with authentic sourdough tang.',
        grade: 'PREMIUM',
        qualityGrade: 'PREMIUM',
        pricePerUnitEtb: 145,
        currency: 'ETB',
        unit: 'KG',
        availableQuantity: 12000,
        minOrderQuantity: 10,
        harvestDate: '2026-08-20',
        productionDate: '2026-08-25',
        expirationDate: '2027-02-25',
        freshnessStatus: 'HARVESTED_RECENTLY',
        expectedAvailability: 'Immediate Dispatch',
        farmLocation: 'Ada’a Farmers Union Milling Facility',
        region: 'Oromia',
        zone: 'East Shewa',
        woreda: 'Ada’a',
        townCity: 'Bishoftu',
        altitudeMeters: 1900,
        ingredients: '100% Pure Ethiopian Super-White Teff Grain (Quncho DZ-Cr-387). Gluten-Free.',
        storageRequirements: 'Store in cool, dry, odor-free pantry.',
        packagingType: '10kg / 25kg Food-Grade Multi-Wall Paper Kraft Sacks',
        images: [
          'https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=800&q=80',
        ],
        lotBatchNumber: 'LOT-AD-TEF-FLR-2026-08',
        qualityScore: 99,
        certifications: ['Gluten-Free Tested', 'Purity Guarantee (Zero Blending)', 'Ethiopian Conformity Assessment Seal'],
        isOrganic: true,
        isVerifiedFarmer: true,
        status: 'ACTIVE',
        shelfLifeDays: 180,
      },

      // 24. PROCESSED FOOD: Traditional Spiced Shiro Milled Flour
      {
        farmerId: farmer3.id,
        farmId: farmsData[2].id,
        categoryId: prodProc,
        name: 'Gojjam Traditional Spiced Shiro Flour Blend',
        subcategory: 'Traditional Spiced Shiro Flour',
        productType: 'PROCESSED_FOOD',
        variety: 'Artisan Roasted Chickpea & Pea Shiro Blend',
        description: 'Premium roasted chickpea and field pea flour stone-ground with traditional Ethiopian sun-cured spices: korarima, dried garlic, ginger, sacred basil (besobila), tena adam, and mild berbere chili. Produces rich, fragrant, silky gourmet Shiro Wot.',
        grade: 'PREMIUM',
        qualityGrade: 'PREMIUM',
        pricePerUnitEtb: 190,
        currency: 'ETB',
        unit: 'KG',
        availableQuantity: 6500,
        minOrderQuantity: 5,
        harvestDate: '2026-08-15',
        productionDate: '2026-08-22',
        expirationDate: '2027-04-22',
        freshnessStatus: 'HARVESTED_RECENTLY',
        expectedAvailability: 'Immediate Dispatch',
        farmLocation: 'Dejen Artisanal Food Processing Cluster',
        region: 'Amhara',
        zone: 'East Gojjam',
        woreda: 'Dejen',
        altitudeMeters: 2300,
        ingredients: 'Roasted chickpeas, split field peas, dried garlic, ginger, korarima, besobila, tena adam, chili pepper, sea salt.',
        storageRequirements: 'Airtight dry container.',
        packagingType: '5kg / 10kg Kraft Bags with Resealable Top',
        images: [
          'https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=800&q=80',
        ],
        lotBatchNumber: 'LOT-GJM-SHR-2026-08',
        qualityScore: 99,
        certifications: ['100% Natural Spices', 'Artisan Women Roasters Seal'],
        isOrganic: true,
        isVerifiedFarmer: true,
        status: 'ACTIVE',
        shelfLifeDays: 240,
      },

      // 25. PROCESSED FOOD: Roasted Ethiopian Barley (Kolo) Snack
      {
        farmerId: farmer3.id,
        farmId: farmsData[2].id,
        categoryId: prodProc,
        name: 'Highland Roasted Barley & Safflower Kolo Snack',
        subcategory: 'Roasted Ethiopian Barley (Kolo)',
        productType: 'PROCESSED_FOOD',
        variety: 'Dejen Roasted Barley with Safflower (Suf)',
        description: 'Crisp, crunchy, golden roasted highland barley hulls blended with nutty roasted safflower seeds and chickpeas. Lightly sea-salted, non-greasy, healthy high-fiber traditional snack.',
        grade: 'GRADE_A',
        qualityGrade: 'GRADE_A',
        pricePerUnitEtb: 160,
        currency: 'ETB',
        unit: 'KG',
        availableQuantity: 3800,
        minOrderQuantity: 5,
        harvestDate: '2026-08-18',
        productionDate: '2026-08-26',
        expirationDate: '2027-05-26',
        freshnessStatus: 'HARVESTED_RECENTLY',
        expectedAvailability: 'Immediate Dispatch',
        farmLocation: 'Dejen Agro-Processing Co-op',
        region: 'Amhara',
        zone: 'East Gojjam',
        woreda: 'Dejen',
        altitudeMeters: 2350,
        ingredients: 'Roasted barley, roasted chickpeas, roasted safflower seeds, sea salt.',
        storageRequirements: 'Store in dry airtight container.',
        packagingType: '1kg / 5kg Vacuum Sealed Stand-Up Pouches',
        images: [
          'https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=800&q=80',
        ],
        lotBatchNumber: 'LOT-GJM-KLO-2026-08',
        qualityScore: 97,
        certifications: ['Food Grade Certified'],
        isOrganic: true,
        isVerifiedFarmer: true,
        status: 'ACTIVE',
        shelfLifeDays: 270,
      },
    ]);

    // ==========================================
    // 8. SEED INPUT PRODUCTS & CART
    // ==========================================
    const inCatSeeds = await db.insert(inputCategories).values([
      { name: 'Certified Hybrid Seeds', slug: 'seeds', icon: 'Sprout' },
      { name: 'Fertilizers & Soil Health', slug: 'fertilizers', icon: 'FlaskConical' },
      { name: 'Crop Protection & Bio-control', slug: 'crop-protection', icon: 'ShieldCheck' },
      { name: 'Irrigation & Solar Systems', slug: 'irrigation', icon: 'Droplets' },
      { name: 'Farm Tools & Machinery', slug: 'tools', icon: 'Wrench' },
    ]).returning();

    const inCat1 = inCatSeeds[0].id;
    const inCat2 = inCatSeeds[1].id;
    const inCat3 = inCatSeeds[3].id;

    await db.insert(inputProducts).values([
      {
        supplierId: 1,
        categoryId: inCat1,
        name: 'Quncho DZ-Cr-387 Certified White Teff Seed',
        brand: 'Ethiopian Seed Enterprise (ESE)',
        description: 'Certified Grade-1 early maturity White Teff seed with 98% germination rate and resistance to lodging.',
        priceEtb: 4800,
        unit: 'BAG (25KG)',
        stockQuantity: 150,
        minOrderQuantity: 1,
        isCertified: true,
        images: ['https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?auto=format&fit=crop&w=800&q=80'],
      },
      {
        supplierId: 1,
        categoryId: inCat2,
        name: 'NPS+Zn Balanced Granular Fertilizer',
        brand: 'EthioAgro Mineral Tech',
        description: 'Specialized blended nitrogen, phosphate, sulfur with zinc micronutrient for Ethiopian volcanic soils.',
        priceEtb: 3950,
        unit: 'BAG (50KG)',
        stockQuantity: 400,
        minOrderQuantity: 2,
        isCertified: true,
        images: ['https://images.unsplash.com/photo-1588879460618-924b172a6b29?auto=format&fit=crop&w=800&q=80'],
      },
      {
        supplierId: 1,
        categoryId: inCat3,
        name: 'Solar-Powered Precision Drip Irrigation Kit',
        brand: 'SunAgri Solutions',
        description: 'Complete 1-Hectare gravity & DC solar pump drip kit with pressure compensating emitters.',
        priceEtb: 145000,
        unit: 'KIT',
        stockQuantity: 25,
        minOrderQuantity: 1,
        isCertified: true,
        images: ['https://images.unsplash.com/photo-1518977676601-b53f82aba655?auto=format&fit=crop&w=800&q=80'],
      },
    ]);

    // Create user carts
    for (const usr of seededUsers) {
      await db.insert(carts).values({ userId: usr.id });
    }

    console.log('AgriLink database seeded successfully with all 13 categories, subcategories, verified farmers, and authentic Ethiopian agricultural products!');
  } catch (error) {
    console.error('Error during database seeding:', error);
  }
}
